# Generated by Django 3.2.12 on 2022-03-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumegame',
            name='position3',
            field=models.BooleanField(default=0),
        ),
    ]
