# Generated by Django 3.2.12 on 2022-03-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_resumegame_position3'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumegame',
            name='topBottom',
            field=models.IntegerField(null=True),
        ),
    ]
