# Generated by Django 3.2.12 on 2022-03-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_resumegame_topbottom'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumegame',
            name='inningHalf',
            field=models.IntegerField(default=0),
        ),
    ]
