# Generated by Django 3.2.12 on 2022-03-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_resumegame_inninghalf'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumegame',
            name='teamSwitching',
            field=models.BooleanField(default=True),
        ),
    ]
