# Generated by Django 3.2.12 on 2022-04-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_resumegame_teamswitching'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumegame',
            name='activeGameStep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumegame',
            name='gameState',
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='resumegame',
            name='hitCount',
            field=models.IntegerField(default=9),
        ),
    ]
